-- Worminator database schema template.
-- Ensure a database exists with a name matching DB_DATABASE in .env.

BEGIN;
 
CREATE TABLE IF NOT EXISTS users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    twitch_id        BIGINT UNIQUE,
    discord_id       BIGINT UNIQUE,
    username         VARCHAR(50) NOT NULL,
    authority_level  INT         NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
 
CREATE TABLE IF NOT EXISTS coaching_sessions
(
    session_id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (user_id),
    session_datetime  TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
 
CREATE TABLE IF NOT EXISTS raffles
(
    raffle_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status            VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'drawn', 'resolved', 'cancelled', 'no winner')),
    duration_seconds  INT         NOT NULL,
    starts_at         TIMESTAMPTZ NOT NULL,
    ends_at           TIMESTAMPTZ,
    winner_id         BIGINT REFERENCES users (user_id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
 
CREATE TABLE IF NOT EXISTS ticket_events
(
    event_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (user_id),
    event_type  VARCHAR(20) NOT NULL
        CHECK (event_type IN ('issued', 'redeem', 'claim', 'raffle_win', 'raffle_loss')),
    amount      INT         NOT NULL,
    raffle_id   BIGINT REFERENCES raffles (raffle_id),
    issued_by   BIGINT      NOT NULL REFERENCES users (user_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
 
COMMIT;
 